config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet  
  belongs_to :user 
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]
  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end
  def new
    @tweet = Tweet.new
  end
  def create
    Tweet.create(tweet_params)
  end
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end
  def edit
  end
  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end
  def show
  end
  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end
  def set_tweet
    @tweet = Tweet.find(params[:id]) 
  end
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title good-chat
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    :javascript
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
  %body
    %header.header
      .header__bar.row
        %h1.grid-6
          = link_to "good-chat", root_path
        - if user_signed_in?
          .user_nav.grid-6
            = link_to "マイページ", user_path(current_user.id)
            = link_to "ログアウト", destroy_user_session_path, method: :delete
            = link_to  "投稿する", new_tweet_path
        - else
          .grid-6
            = link_to "ログイン", new_user_session_path, class: 'post'
            = link_to "新規登録", new_user_registration_path, class: 'post'
    = yield
    %footer
      %p
        Copyright good-chat 2020.

app/views/tweets/create.html.haml
.contents.row
  .success
    %h3
      投稿が完了しました。
    = link_to "投稿一覧へ戻る" ,root_path ,claas: "btn"

app/views/tweets/destroy.html.haml
.contents.row
  .success
    %h3
      削除が完了しました。
    = link_to "投稿一覧へ戻る" ,root_path ,claas: "btn"

app/views/tweets/edit.html.haml
.contents.row
  .container
    = form_with(model: @tweet, local: true) do |form|
      %h3
        編集する
      = form.text_field :image, placeholder: "Image Url"
      = form.text_area :text, placeholder: "text" , rows: "10"
      = form.submit "SEND"

app/views/tweets/index.html.haml
.contents.row
  - @tweets.each do |tweet|
    .content_post{:style => "background-image: url(#{tweet.image});"}
      .more
        %ul.more_list
          %li
            = link_to '詳細', "/tweets/#{tweet.id}", method: :get
          - if user_signed_in? && current_user.id == tweet.user_id
            %li
              = link_to '編集', "/tweets/#{tweet.id}/edit", method: :get
            %li
              = link_to '削除', "/tweets/#{tweet.id}", method: :delete
      = simple_format(tweet.text)
      %span.name
        %a{:href => "/users/#{tweet.user.id}"}
          %span 投稿者
          = tweet.user.nickname
  = paginate(@tweets)

app/views/tweets/new.html.haml
.contents.row
  .container
    = form_with(model: @tweet, local: true) do |form|
      %h3
        投稿する
      = form.text_field :image, placeholder: "Image Url"
      = form.text_area :text, placeholder: "text" , rows: "10"
      = form.submit "SEND"

app/views/tweets/show.html.haml
.contents.row
  .content_post{:style => "background-image: url(#{@tweet.image});"}
    - if user_signed_in? && current_user.id == @tweet.user_id
      .more
        %ul.more_list
          %li
            = link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get
          %li
            = link_to '削除', "/tweets/#{@tweet.id}", method: :delete
    = simple_format(@tweet.text)
    %span.name
      %a{:href => "/users/#{@tweet.user.id}"}
        %span 投稿者
        = @tweet.user.nickname

app/views/tweets/update.html.haml
.contents.row
  .success
    %h3
      更新が完了しました。
    = link_to "投稿一覧へ戻る" ,root_path ,claas: "btn"

app/views/users/show.html.haml
.contents.row
  %p
    = @nickname
    さんの投稿一覧
  - @tweets.each do |tweet|
    .content_post{:style => "background-image: url(#{tweet.image});"}
      = simple_format(tweet.text)